#!/bin/sh
#
# Start lvgl....
#


start() {
        if mount | grep /mnt; then
            echo "/mnt is mounted."
        else
            mount -t nfs -o nolock,vers=3 192.168.5.11:/home/book/nfs_rootfs /mnt
        fi
        printf "Starting 100ask lvgl: "
        eval `dbus-launch --auto-syntax`
        echo -e "\033[9;0]" > /dev/tty0
        echo -n -e '\e[?17;14;224c'
        echo 0 > /sys/class/graphics/fbcon/cursor_blink
        psplash-write "QUIT"
        start-stop-daemon -S -q -m -b -p /var/run/lvgl.pid \
                        -x /mnt/lv_100ask_demo
      [ $? = 0 ] && echo "OK" || echo "FAIL"
}

stop() {
        printf "Stopping lvgl: "
        start-stop-daemon -K -q -p /var/run/lvgl.pid \
                          -x /mnt/lv_100ask_demo
        [ $? = 0 ] && echo "OK" || echo "FAIL"
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart|reload)
        stop
        start
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
